all: feature_extraction generate_size_marker generate_size_histogram generate_num_marker generate_html_marker generate_label
CC=gcc

fe_objects = fe_total_pkt_up.o fe_total_pkt_down.o fe_percent_up.o fe_percent_down.o fe_total_byte_down.o fe_total_byte_up.o fe_html_markers.o fe_size_markers.o fe_num_markers.o fe_size_histogram.o fe_total_time.o fe_raw_meta_info.o fe_component_vectors.o fe_two_d_space.o fe_one_d_space.o default_fe.o fe_unique_up.o fe_unique_down.o feature_config.o countable_set.o pcap_helper.o

fe_headers = feature_extraction.h feature_config.h pcap_helper.h countable_set.h

generate_label: generate_label.o
	$(CC) generate_label.o -o generate_label

generate_label.o: generate_label.c
	$(CC) -c generate_label.c -o generate_label.o

feature_extraction: $(fe_objects) feature_extraction.o
	$(CC) -o feature_extraction $(fe_objects) feature_extraction.o -lpcap -lm

feature_extraction.o: $(fe_objects) feature_extraction.c
	$(CC) -c feature_extraction.c -o feature_extraction.o -lpcap -lm

fe_total_pkt_up.o: $(fe_headers) fe_total_pkt_up.c
	$(CC) -c fe_total_pkt_up.c -o fe_total_pkt_up.o

fe_total_pkt_down.o: $(fe_headers) fe_total_pkt_down.c
	$(CC) -c fe_total_pkt_down.c -o fe_total_pkt_down.o

fe_percent_up.o: $(fe_headers) fe_percent_up.c
	$(CC) -c fe_percent_up.c -o fe_percent_up.o

fe_percent_down.o: $(fe_headers) fe_percent_down.c
	$(CC) -c fe_percent_down.c -o fe_percent_down.o

fe_total_byte_down.o: $(fe_headers) fe_total_byte_down.c
	$(CC) -c fe_total_byte_down.c -o fe_total_byte_down.o

fe_total_byte_up.o: $(fe_headers) fe_total_byte_up.c
	$(CC) -c fe_total_byte_up.c -o fe_total_byte_up.o

fe_html_markers.o: $(fe_headers) fe_html_markers.c
	$(CC) -c fe_html_markers.c -o fe_html_markers.o

fe_size_markers.o: $(fe_headers) fe_size_markers.c
	$(CC) -c fe_size_markers.c -o fe_size_markers.o

fe_num_markers.o: $(fe_headers) fe_num_markers.c
	$(CC) -c fe_num_markers.c -o fe_num_markers.o

fe_size_histogram.o: $(fe_headers) fe_size_histogram.c
	$(CC) -c fe_size_histogram.c -o fe_size_histogram.o

fe_total_time.o: $(fe_headers) fe_total_time.c
	$(CC) -c fe_total_time.c -o fe_total_time.o

fe_raw_meta_info.o: $(fe_headers) fe_raw_meta_info.c
	$(CC) -c fe_raw_meta_info.c -o fe_raw_meta_info.o

fe_component_vectors.o: $(fe_headers) fe_component_vectors.c
	$(CC) -c fe_component_vectors.c -o fe_component_vectors.o

fe_two_d_space.o: $(fe_headers) fe_two_d_space.c
	$(CC) -c fe_two_d_space.c -o fe_two_d_space.o

fe_one_d_space.o: $(fe_headers) fe_one_d_space.c
	$(CC) -c fe_one_d_space.c -o fe_one_d_space.o

default_fe.o: $(fe_headers) default_fe.c
	$(CC) -c default_fe.c -o default_fe.o

fe_unique_up.o: $(fe_headers) fe_unique_up.c
	$(CC) -c fe_unique_up.c -o fe_unique_up.o

fe_unique_down.o: $(fe_headers) fe_unique_down.c
	$(CC) -c fe_unique_down.c -o fe_unique_down.o

feature_config.o: $(fe_headers) feature_config.c
	$(CC) -c feature_config.c -o feature_config.o

countable_set.o: $(fe_headers) countable_set.c
	$(CC) -c countable_set.c -o countable_set.o

pcap_helper.o: $(fe_headers) pcap_helper.c
	$(CC) -c pcap_helper.c -o pcap_helper.o

round_double.o: $(fe_headers) round_double.c
	$(CC) -c round_double.c -o round_double.o

generate_size_marker: generate_size_marker.o pcap_helper.o countable_set.o round_double.o
	$(CC) generate_size_marker.o pcap_helper.o countable_set.o round_double.o -o generate_size_marker -lpcap -lm

generate_size_marker.o: generate_size_marker.c pcap_helper.o countable_set.o round_double.o
	$(CC) -c generate_size_marker.c -o generate_size_marker.o -lpcap -lm

generate_num_marker: generate_num_marker.o pcap_helper.o countable_set.o round_double.o
	$(CC) generate_num_marker.o pcap_helper.o countable_set.o round_double.o -o generate_num_marker -lpcap -lm

generate_num_marker.o: generate_num_marker.c pcap_helper.o countable_set.o round_double.o
	$(CC) -c generate_num_marker.c -o generate_num_marker.o -lpcap -lm

generate_size_histogram: generate_size_histogram.o pcap_helper.o countable_set.o round_double.o
	$(CC) generate_size_histogram.o pcap_helper.o countable_set.o round_double.o -o generate_size_histogram -lpcap -lm

generate_size_histogram.o: generate_size_histogram.c pcap_helper.o countable_set.o round_double.o
	$(CC) -c generate_size_histogram.c -o generate_size_histogram.o -lpcap -lm

generate_html_marker: generate_html_marker.o pcap_helper.o countable_set.o round_double.o
	$(CC) generate_html_marker.o pcap_helper.o countable_set.o round_double.o -o generate_html_marker -lpcap -lm

generate_html_marker.o: generate_html_marker.c pcap_helper.o countable_set.o round_double.o
	$(CC) -c generate_html_marker.c -o generate_html_marker.o -lpcap -lm

clean:
	rm -rf *.o feature_extraction generate_size_marker generate_html_marker generate_num_marker generate_size_histogram
